<?php

namespace App\Http\Controllers\api\v1;

use App\Http\Requests\File\StoreMultipleRequest;
use App\Http\Requests\File\StoreRequest;
use App\Http\Requests\File\UpdateMultipleRequest;
use App\Http\Requests\File\UpdateRequest;
use App\Models\File;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class FilesController extends ApiBaseController
{
    /**
     * Display a listing of the files with optional filters.
     */
    public function index(Request $request): JsonResponse
    {
        $query = File::with(['user']);

        if ($request->filled('type')) {
            $query->byType($request->type);
        }

        if ($request->filled('user_id')) {
            $query->byUser($request->user_id);
        }

        if ($request->filled('is_active')) {
            $query->where('is_active', $request->is_active);
        }

        if ($request->filled('from_date') && $request->filled('to_date')) {
            $query->dateBetween($request->from_date, $request->to_date);
        }

        if ($request->filled('search')) {
            $query->search($request->search);
        }

        $files = $query->latest()->paginate($request->get('per_page', 15));

        return $this->okResponse(['files' => $files], __('Files retrieved with filters.'));
    }

    /**
     * Display the specified file.
     */
    public function show(int $id): JsonResponse
    {
        $file = File::with(['user'])->find($id);

        if (! $file) {
            return $this->notFoundResponse([], __('File not found.'));
        }

        if ($file->is_deleted) {
            return $this->notFoundResponse([], __('File has been deleted.'));
        }

        return $this->okResponse(['file' => $file], __('File retrieved successfully.'));
    }

    /**
     * Store a newly created file in storage.
     */
    public function store(StoreRequest $request): JsonResponse
    {
        DB::beginTransaction();

        try {
            $uploadedFile = $request->file('file');

            // Use the trait method to upload file
            $path = $this->uploadFile($uploadedFile, 'uploads');

            // Create the file record
            $file = File::create(array_merge([
                'name' => $request->name,
                'path' => $path,
            ], $request->autoGeneratedAttributes()));

            // Commit the transaction
            DB::commit();

            // Return the created file
            return $this->createdResponse(['file' => $file], __('File uploaded successfully.'));
        } catch (\Throwable $e) {
            // Rollback the transaction in case of error
            DB::rollBack();

            // Log the error with additional context
            Log::error('File upload failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => auth()->id(),
            ]);

            // Return an error response
            return $this->serverErrorResponse([], __('Failed to upload file.'));
        }
    }

    /**
     * Store multiple files in storage.
     */
    public function storeMultiple(StoreMultipleRequest $request): JsonResponse
    {
        DB::beginTransaction();

        try {
            $files = [];
            foreach ($request->file('files') as $uploadedFile) {
                // Use the trait method to upload file
                $path = $this->uploadFile($uploadedFile, 'uploads');

                // Create the file record
                $file = File::create(array_merge([
                    'name' => $uploadedFile->getClientOriginalName(),
                    'path' => $path,
                ], $request->autoGeneratedAttributes()));

                $files[] = $file;
            }

            // Commit the transaction
            DB::commit();

            // Return the created files
            return $this->createdResponse(['files' => $files], __('Files uploaded successfully.'));
        } catch (\Throwable $e) {
            // Rollback the transaction in case of error
            DB::rollBack();

            // Log the error with additional context
            Log::error('Multiple file upload failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => auth()->id(),
            ]);

            // Return an error response
            return $this->serverErrorResponse([], __('Failed to upload files.'));
        }
    }

    /**
     * Update the specified file in storage.
     */
    public function update(UpdateRequest $request, int $id): JsonResponse
    {
        DB::beginTransaction();

        try {
            $file = File::find($id);

            if (! $file) {
                return $this->notFoundResponse([], __('File not found.'));
            }

            // Handle file upload if a new file is provided
            $uploadedFile = $request->file('file');
            if ($uploadedFile) {
                if ($file->path && $this->checkExistsFile($file->path)) {
                    $this->removeFile($file->getRawOriginal('path'));
                }

                $path = $this->uploadFile($uploadedFile, 'uploads');
                $file->path = $path;
            }

            // Update the file record
            $file->update(array_merge($request->validated(), [
                'name' => $request->name,
            ]));

            // Commit the transaction
            DB::commit();

            // Return the updated file
            return $this->okResponse(['file' => $file], __('File updated successfully.'));
        } catch (\Throwable $e) {
            // Rollback the transaction in case of error
            DB::rollBack();

            // Log the error with additional context
            Log::error('File update failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => auth()->id(),
            ]);

            // Return an error response
            return $this->serverErrorResponse([], __('Failed to update file.'));
        }
    }

    public function updateMultiple(UpdateMultipleRequest $request): JsonResponse
    {
        DB::beginTransaction();

        try {
            $files = [];
            foreach ($request->file('files') as $uploadedFile) {
                $file = File::find($uploadedFile['id']);

                if (! $file) {
                    return $this->notFoundResponse([], __('File not found for ID: :id', ['id' => $uploadedFile['id']]));
                }

                if ($file->path && $this->checkExistsFile($file->path)) {
                    $this->removeFile($file->getRawOriginal('path'));
                }

                // Use the trait method to upload file
                $path = $this->uploadFile($uploadedFile, 'uploads');

                // Update the file record
                $file->update(array_merge([
                    'name' => $uploadedFile->getClientOriginalName(),
                    'path' => $path,
                ], $request->autoGeneratedAttributes()));

                $files[] = $file;
            }

            // Commit the transaction
            DB::commit();

            // Return the created files
            return $this->createdResponse(['files' => $files], __('Files uploaded successfully.'));
        } catch (\Throwable $e) {
            // Rollback the transaction in case of error
            DB::rollBack();

            // Log the error with additional context
            Log::error('Multiple file upload failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => auth()->id(),
            ]);

            // Return an error response
            return $this->serverErrorResponse([], __('Failed to upload files.'));
        }
    }

    /**
     * Remove the specified file from storage.
     */
    public function destroy(int $id): JsonResponse
    {
        $file = File::find($id);

        if (! $file) {
            return $this->notFoundResponse([], __('File not found.'));
        }

        // Check if the file exists and remove it
        if ($file->path && $this->checkExistsFile($file->path)) {
            $this->removeFile($file->getRawOriginal('path'));
        }

        // Delete the file record
        $file->delete();

        return $this->okResponse([], __('File deleted successfully.'));
    }
}
